
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xqpp.h"

/*
* The configuration table for devices
*/

XQpp_Config XQpp_ConfigTable[XPAR_XQPP_NUM_INSTANCES] =
{
	{
		XPAR_QPP_0_DEVICE_ID,
		XPAR_QPP_0_S_AXI_CONTROL_R_BASEADDR
	}
};


